version: '3.8'
services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./src/requirements/mariadb
      dockerfile: dockerfile
    volumes:
      - mariadb-db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my_network

  nginx:
    container_name: nginx
    depends_on:
      - "mariadb"
      - "wordpress"
    build:
      context: ./src/requirements/nginx
      dockerfile: dockerfile
    ports:
      - 80:80
    volumes:
      - wordPress-db:/var/www/html/
      - nginx_db:/etc/nginx
    env_file:
      - .env
    networks:
      - my_network

  wordpress:
    container_name: wordpress
    depends_on:
      - "mariadb"
    build:
      context: ./src/requirements/wordpress
      dockerfile: dockerfile
    volumes:
      - wordPress-db:/var/www/html/
    env_file:
      - .env
    networks:
      - my_network

volumes:
  mariadb-db:
    name: mariadb-db
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  nginx_db:
    name: nginx_db
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/nginx
      o: bind
  wordPress-db:
    name: wordPress-db
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wp
      o: bind

networks:
  my_network:
    name: my_network
    driver: bridge
