FROM debian:bookworm

RUN apt update -y
RUN apt install -y wget; apt install -y php-fpm php-mysql mariadb-client;
RUN sed -i 's/listen = \/run\/php\/php8.2-fpm.sock/listen = 0.0.0.0:9000/' /etc/php/8.2/fpm/pool.d/www.conf;

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

COPY ./tools/entrypoint_script.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint_script.sh

WORKDIR /var/www/html
RUN chmod -R 755 /var/www/html/
RUN chown -R www-data:www-data /var/www/html/

EXPOSE 9000

# RUN wp core download --allow-root
# RUN wp core download --path=/var/www/html --locale=en_US --allow-root;

ENTRYPOINT ["entrypoint_script.sh"]

CMD ["php-fpm8.2", "-F"]