FROM debian:bookworm

RUN apt update 
RUN apt install -y wget

RUN apt install -y php-fpm php-mysql
RUN sed -i 's/listen = \/run\/php\/php8.2-fpm.sock/listen = 0.0.0.0:9000/' /etc/php/8.2/fpm/pool.d/www.conf;

RUN mkdir -p /var/www/html

RUN mkdir -p /var/www/html/adminer

RUN wget "http://www.adminer.org/latest.php" -O /var/www/html/adminer/adminer.php

COPY ./tools/entrypoint_script.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/entrypoint_script.sh

ENTRYPOINT ["entrypoint_script.sh"]

CMD ["php-fpm8.2", "-F"]