FROM debian:bookworm

RUN apt update 
RUN apt install -y curl

RUN apt install -y php-fpm

WORKDIR /var/www/html

RUN curl -o https://github.com/vrana/adminer/releases/download/v4.7.8/adminer-4.7.8.php

CMD ["php-fpm8.2", "-F"]