FROM debian:bookworm

RUN apt update 
RUN apt upgrade -y
RUN apt install -y mariadb-server 

RUN mkdir -p /run/mysqld/ && \
    chown mysql:mysql /run/mysqld/

COPY ./tools/entrypoint_script.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/entrypoint_script.sh

ENTRYPOINT ["entrypoint_script.sh"]

CMD ["mariadbd", "--user=mysql"] 
