FROM debian:bookworm

RUN apt update

RUN apt install -y nginx

RUN apt install -y vim

COPY ./conf/configuration.conf /etc/nginx/sites-available/configuration.conf

RUN rm /etc/nginx/sites-enabled/*

RUN ln -s /etc/nginx/sites-available/configuration.conf /etc/nginx/sites-enabled/

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]