FROM debian:bookworm

RUN apt update 
RUN apt upgrade -y

RUN apt install -y python3
RUN apt install -y python3-pip
RUN apt install -y git
RUN rm /usr/lib/python3.11/EXTERNALLY-MANAGED
RUN pip install django
WORKDIR /var/www/html

COPY ./tools/entrypoint_script.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint_script.sh

ENTRYPOINT ["entrypoint_script.sh"]

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]