version: '3.8'
services:
  django:
    container_name: django
    build:
      context: ./django_img
      dockerfile: dockerfile
    volumes:
      - django_db:/var/www/html/demo
    networks:
      - django_network
    ports:
      - 8000:8000

volumes:
  django_db:
    name: django_db
    driver: local
    driver_opts:
      type: none
      device: ./database
      o: bind

networks:
  django_network:
    name: django_network
    driver: bridge
