# Use the official Debian base image
FROM debian:latest

# Install MariaDB server and client
RUN apt-get update && \
    apt-get install -y mariadb-server mariadb-client && \
    rm -rf /var/lib/apt/lists/*

# Expose the MySQL port
EXPOSE 3306

# CMD instruction to start MariaDB when the container runs
# CMD ["mysqld"]