version: '3.8'
services:
  django:
    container_name: django
    build:
      context: ./requirements/bonus/django
      dockerfile: dockerfile
    volumes:
      - django_db:/var/www/html
    networks:
      - my_network
    ports:
      - 8000:8000

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: dockerfile
    volumes:
      - mariadb_db:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - my_network
    
  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: dockerfile
    networks:
      - my_network

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
      dockerfile: dockerfile
    volumes:
      - wordPress_db:/wordPress_db
    networks:
      - my_network
    depends_on:
      - "wordpress"

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: dockerfile
    volumes:
      - wordPress_db:/var/www/html/
    networks:
      - my_network
    depends_on:
      - "wordpress"
      - "mariadb"

  wordpress:
    container_name: wordpress
    depends_on:
      - "mariadb"
      - "redis"
    build:
      context: ./requirements/wordpress
      dockerfile: dockerfile
    volumes:
      - wordPress_db:/var/www/html/
    env_file:
      - ./.env
    networks:
      - my_network

  nginx:
    container_name: nginx
    depends_on:
      - "mariadb"
      - "wordpress"
      - "adminer"
    build:
      context: ./requirements/nginx
      dockerfile: dockerfile
    ports:
      - 443:443
    volumes:
      - wordPress_db:/var/www/html/
    env_file:
      - ./.env
    networks:
      - my_network

volumes:
  mariadb_db:
    name: mariadb_db
    driver: local
    driver_opts:
      type: none
      device: /workspaces/inception/data/mariadb
      o: bind
  wordPress_db:
    name: wordPress_db
    driver: local
    driver_opts:
      type: none
      device: /workspaces/inception/data/wp
      o: bind
  django_db:
    name: django_db
    driver: local
    driver_opts:
      type: none
      device: /workspaces/inception/data/django
      o: bind

networks:
  my_network:
    name: my_network
    driver: bridge


# /home/${USER}/data/wp