version: '3.8'
services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: dockerfile
    volumes:
      - mariadb_db:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - my_network
    
  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: dockerfile
    networks:
      - my_network

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
      dockerfile: dockerfile
    volumes:
      - wordPress_db:/wordPress_db:ro
    networks:
      - my_network
    # ports:
    #   - "21:21"
    #   # - "20:20"

  wordpress:
    container_name: wordpress
    depends_on:
      - "mariadb"
      - "redis"
    build:
      context: ./requirements/wordpress
      dockerfile: dockerfile
    volumes:
      - wordPress_db:/var/www/html/
    env_file:
      - ./.env
    networks:
      - my_network

  nginx:
    container_name: nginx
    depends_on:
      - "mariadb"
      - "wordpress"
    build:
      context: ./requirements/nginx
      dockerfile: dockerfile
    ports:
      - 443:443
    volumes:
      - wordPress_db:/var/www/html/
    env_file:
      - ./.env
    networks:
      - my_network

volumes:
  mariadb_db:
    name: mariadb_db
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordPress_db:
    name: wordPress_db
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wp
      o: bind

networks:
  my_network:
    name: my_network
    driver: bridge
