version: '3.8'
services:
  django:
    container_name: django
    build:
      context: ./requirements/bonus/django
      dockerfile: dockerfile
    image: django
    volumes:
      - django_db:/var/www/html
    networks:
      - my_network
    ports:
      - 8000:8000

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: dockerfile
    image: mariadb
    volumes:
      - mariadb_db:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - my_network
    secrets:
      - mariadb_pass
    
  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: dockerfile
    image: redis
    networks:
      - my_network

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
      dockerfile: dockerfile
    image: ftp
    volumes:
      - wordPress_db:/wordPress_db
    networks:
      - my_network
    depends_on:
      - "wordpress"
    env_file:
      - ./.env
    secrets:
      - ftp_pass

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: dockerfile
    image: adminer
    volumes:
      - wordPress_db:/var/www/html/
    networks:
      - my_network
    depends_on:
      - "wordpress"
      - "mariadb"

  wordpress:
    container_name: wordpress
    depends_on:
      - "mariadb"
      - "redis"
    build:
      context: ./requirements/wordpress
      dockerfile: dockerfile
    image: wordpress
    volumes:
      - wordPress_db:/var/www/html/
    env_file:
      - ./.env
    networks:
      - my_network
    secrets:
      - mariadb_pass
      - admin_pass
      - user_pass

  cadvisor:
    container_name: cadvisor
    build: 
      context: ./requirements/bonus/cadvisor
      dockerfile: dockerfile
    image: cadvisor
    networks:
      - my_network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  nginx:
    container_name: nginx
    depends_on:
      - "mariadb"
      - "wordpress"
      - "adminer"
      - "cadvisor"
    build:
      context: ./requirements/nginx
      dockerfile: dockerfile
    image: nginx
    ports:
      - 443:443
    volumes:
      - wordPress_db:/var/www/html/
    env_file:
      - ./.env
    networks:
      - my_network
    secrets:
      - rrasezin.42.fr.cert
      - rrasezin.42.fr.key
    restart: always

volumes:
  mariadb_db:
    name: mariadb_db
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind
  wordPress_db:
    name: wordPress_db
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wp
      o: bind
  django_db:
    name: django_db
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/django
      o: bind

networks:
  my_network:
    name: my_network
    driver: bridge

secrets:
  mariadb_pass:
    file: ./../secrets/mariadb_pass.txt
  admin_pass:
    file: ./../secrets/admin_pass.txt
  user_pass:
    file: ./../secrets/user_pass.txt
  ftp_pass:
    file: ./../secrets/ftp_pass.txt
  rrasezin.42.fr.cert:
    file: ./../secrets/rrasezin.42.fr.cert
  rrasezin.42.fr.key:
    file: ./../secrets/rrasezin.42.fr.key